server:
  port: 8082
spring:
  application:
    name: LikeApi
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    sleuth:
      sampler:
        probability: 1  #采样率 Sleuth
    zipkin:
      sender:
        type: web   #通过http协议推送数据
      base-url: http://localhost:9411  #Zipkin可视化服务地址  Zipkin-server
      service:
        name: offer-api

