server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery: #实现注册于发现服务
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloudoffer?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*.xml
